### ISSUE TITLE
Wrong login/password

### ISSUE THREAD

**Issue by FPSychotic** [day0wl/libresdr-fw#1]
Hi, I bought this device. It has already flashed in internal memory the Pluto Firmware. The ADI chip is locked at 3.8ghz. Im trying connect via putty to unlock the 6ghz, and I need login.
Official firmware is root/analog, but doesnt work , tried analog/analog, and many others , but doesn't work. 
Could you please tell me if it is the official firmware what is the password?
Thanks

**Comment by day0wl** [comment]
Hi, appreciate the info. It is not an official firmware, but a fairly incomplete, but functional port of the vanilla Pluto SDR firmware onto LibreSDR. It is not compatible with the original Pluto or Pluto+.
Unfortunately I have no knowledge of what could be programmed into the devices now, all samples I have came with some software on the SD card. Please contact the seller, usually they are fairly responsive.
If you have the LibreSDR aka ZynqSDR, can be recognized by unpainted aluminum case with LibreSDR markings, the SD Card boot takes precedent, regardless of what is flashed into the internal QSFP.
There is an enhanced port which you can try https://github.com/hz12opensource/libresdr
It has prebuilt images and allows greater speed by activation of the LVDS interface to the ADI chip and CPU overclocking. 
There is nothing else I can help with, closing
